<h1>Pandas: Series</h1>

In [1]:
import pandas as pd

x = [3,4,5,6]
ser = pd.Series(x)
index = pd.Series(x, index=['a','b','c','d'])      #to change index of table by default it's 0-->n
datatype = pd.Series(x, index=['a','b','c','d'], dtype='float')     #convert to float 
name = pd.Series(x, index=['a','b','c','d'], dtype='float', name ='python')    # give specific name to dataset

print(ser)
print(index)
print(datatype)
print(name)

print(ser[2])        #to get element of array
print(index['b'])   # we can access the elements using index of table

0    3
1    4
2    5
3    6
dtype: int64
a    3
b    4
c    5
d    6
dtype: int64
a    3.0
b    4.0
c    5.0
d    6.0
dtype: float64
a    3.0
b    4.0
c    5.0
d    6.0
Name: python, dtype: float64
5
4


In [2]:
dic = {"name":['python','c','c++','java'], "por":[12,13,14,15], "rank":[1,4,3,2]}
var1 = pd.Series(dic) 
var1

name    [python, c, c++, java]
por           [12, 13, 14, 15]
rank              [1, 4, 3, 2]
dtype: object

In [3]:
import pandas as pd
s = pd.Series(12)            # create series of 12 at 0th position 
m = pd.Series(12, index = [1,2,3,4,5,6,7,8]) #create series for 12 at given index position
print(s)
print(m)

0    12
dtype: int64
1    12
2    12
3    12
4    12
5    12
6    12
7    12
8    12
dtype: int64


In [4]:
#if we need to add two Series data it will add likw below.but it will add up to same
#index which is present in both series. (size should be same ) else it print NaN(not a number)
#in numpy if we did this we got broadcast error. but pandas will support this. 

m = pd.Series(12, index = [1,2,3,4,5,6,7,8])
n = pd.Series(12, index = [1,2,3,4])
print((m + n))

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64


<h1>Pandas: DataFrame

In [5]:
import pandas as pd
list1 = [1,2,3,4,5,6]
var = pd.DataFrame(list1)
print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>


In [6]:
dictionary = {"a":[1,2,3,14,5], "s":[1,2,3,4,5],"d":[1,2,3,4,5],1:[1,2,3,4,5]}
var1 = pd.DataFrame(dictionary)
print(var1)

print(var1["a"][3])  #get specific element from DataFrame

var2 = pd.DataFrame(dictionary, columns=["a"]) #print only column a 
print(var2)

    a  s  d  1
0   1  1  1  1
1   2  2  2  2
2   3  3  3  3
3  14  4  4  4
4   5  5  5  5
14
    a
0   1
1   2
2   3
3  14
4   5


In [7]:
list_1 = [ [1,2,3,4,5], [11,12,13,14,15] ]
v = pd.DataFrame(list_1)
v

0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [8]:
sr = {
    "s":pd.Series([1,2,3,4]), 
    "r":pd.Series([5,6,7,8])}
n = pd.DataFrame(sr)
print(n)

   s  r
0  1  5
1  2  6
2  3  7
3  4  8


In [9]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [10]:
print(myvar.loc[0])     # to get rows from DataFrame use loc[] function, it will return a Series

calories    420
duration     50
Name: 0, dtype: int64


In [11]:
print(myvar.loc[[0 , 1]])   ## to get rows from DataFrame use loc[[]] function with [] , it will return a DataFrame

   calories  duration
0       420        50
1       380        40


<h1>Pandas: Arithmetic operation

In [12]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8


In [13]:
import pandas as pd 
var = pd.DataFrame(
    {
        "A":[1,2,3,4], "B":[5,6,7,8]
    })
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8


In [14]:
var["C"] = var["A"] + var["B"]    #addition of both column
print(var)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12


In [15]:
var["D"] = var["A"] - var["B"]    #substraction of both column
print(var)

   A  B   C  D
0  1  5   6 -4
1  2  6   8 -4
2  3  7  10 -4
3  4  8  12 -4


In [16]:
var1 = pd.DataFrame({"A":[10,20,30,40], "B":[50,60,70,80]})
print(var1)



    A   B
0  10  50
1  20  60
2  30  70
3  40  80


In [17]:
var1["python"] = var1["A"] <= 20     #create new column named as "python" and check if data in column "A" is less than 20
print(var1)

    A   B  python
0  10  50    True
1  20  60    True
2  30  70   False
3  40  80   False


In [18]:
var1["python_1"] = var1["B"] >= 60     #create new column named as "python_1" and check if data in column "B" is greater than 60
print(var1)

    A   B  python  python_1
0  10  50    True     False
1  20  60    True      True
2  30  70   False      True
3  40  80   False      True


<h1>Insert 

In [19]:
import pandas as pd 
var = pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[6,7,8,9,10]
})
print(var)

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10


In [20]:

var.insert(1,"python", [11,12,13,14.15])  #insert given data at 1th position in dataframe with column name as python.
print(var)

ValueError: Length of values (4) does not match length of index (5)

In [ ]:
var["python_1"] = var["A"][0:3]    #copy 0 to 3 data from column "A" and  add in a python-1 column.
print(var)

NameError: name 'var' is not defined

<h1>Delete

In [ ]:
import pandas as pd 
data = pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[6,7,8,9,10],
    "C":[11,12,13,14,15],
    "E":[20,21,22,23,24]
})
print(data)

   A   B   C   E
0  1   6  11  20
1  2   7  12  21
2  3   8  13  22
3  4   9  14  23
4  5  10  15  24


In [ ]:
pop = data.pop("B") #for pop we use () with column to be delete
print(pop)

0     6
1     7
2     8
3     9
4    10
Name: B, dtype: int64


In [ ]:
print(data)

   A   C   E
0  1  11  20
1  2  12  21
2  3  13  22
3  4  14  23
4  5  15  24


In [ ]:
del data["E"]   #for delete we use [] with column to be delete

In [ ]:
print(data)

   A   C
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15


<h1> Create CSV file

In [ ]:
import pandas as pd
dic = {"a":[1,2,3,4,5], "b":[1,2,3,4,5],"c":[1,2,3,4,5]}
frame = pd.DataFrame(dic)
print(frame)

frame.to_csv("Test.csv") #create csv file named Test.csv
frame.to_csv("Test_new.csv", index = False) #remove index
frame.to_csv("Test_new1.csv", index= False, header=[1,2,3]) #rename column name using header


   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5


<h1>Read CSV 


In [ ]:
import pandas as pd 
read_csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Test_new.csv")
print(read_csv)


   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5


In [ ]:
import pandas as pd 
read_csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Test_new.csv",nrows=2)  # to get no of rows then use 'nrows'
print(read_csv)

read_csv_1 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", usecols=["Age"])  # to get perticuler column in csv file use "usecols=["column_name"]"
print(read_csv_1)

read_csv_2 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", usecols=[2])  # to get perticuler column in csv file we can give interger position of column also.
print(read_csv_2)


   a  b  c
0  1  1  1
1  2  2  2
     Age
0     17
1     18
2     15
3     17
4     17
..   ...
143   18
144   18
145   17
146   17
147   17

[148 rows x 1 columns]
     Gender
0         1
1         0
2         0
3         1
4         1
..      ...
143       0
144       0
145       1
146       1
147       0

[148 rows x 1 columns]


In [ ]:
read_csv_3 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", skiprows=[0])  #using this we can skip rows in a csv file
print(read_csv_3)

     1001  17  1  0  2  19.833722807854713   7  1.1  2.1  0.1  0.2  1.2  0.3  \
0    1002  18  0  0  1           15.408756   0    0    1    0    0    0    0   
1    1003  15  0  2  3            4.210570  26    0    2    0    0    0    0   
2    1004  17  1  0  3           10.028829  14    0    3    1    0    0    0   
3    1005  17  1  0  2            4.672495  17    1    3    0    0    0    0   
4    1006  18  0  0  1            8.191219   0    0    1    1    0    0    0   
..    ...  .. .. .. ..                 ...  ..  ...  ...  ...  ...  ...  ...   
142  1144  18  0  2  1           18.978324  16    0    2    1    0    1    0   
143  1145  18  0  2  2            4.919995   7    1    2    1    1    0    0   
144  1146  17  1  0  3           10.641736   9    0    3    1    0    0    0   
145  1147  17  1  2  2            9.647124   1    1    2    1    0    0    1   
146  1148  17  0  2  1           14.057329  11    0    3    0    1    0    0   

     2.929195591667681  2.0  
0        

In [21]:
read_csv_4 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv",index_col=["Age"])  #using this we can use Age column as a index in a file .rather than using original index.
print(read_csv_4)

     StudentID  Gender  Ethnicity  ParentalEducation
Age                                                 
17        1001       1          0                  2
18        1002       0          0                  1
15        1003       0          2                  3
17        1004       1          0                  3
17        1005       1          0                  2
18        1006       0          0                  1
15        1007       0          1                  1
15        1008       1          1                  4
17        1009       0          0                  0
16        1010       1          0                  1
17        1011       0          0                  1
17        1012       0          0                  1
17        1013       0          1                  1
17        1014       0          1                  2
18        1015       1          0                  1
15        1016       0          0                  2
18        1017       0          3             

In [25]:
import pandas as pd
read_csv_5 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv",header=2)  #using this we can use second column as a header in a file.
print(read_csv_5)

    1002  18  0  0.1  1
0   1003  15  0    2  3
1   1004  17  1    0  3
2   1005  17  1    0  2
3   1006  18  0    0  1
4   1007  15  0    1  1
5   1008  15  1    1  4
6   1009  17  0    0  0
7   1010  16  1    0  1
8   1011  17  0    0  1
9   1012  17  0    0  1
10  1013  17  0    1  1
11  1014  17  0    1  2
12  1015  18  1    0  1
13  1016  15  0    0  2
14  1017  18  0    3  1
15  1018  18  1    0  0
16  1019  18  0    1  3
17  1020  17  0    0  1
18  1021  16  1    0  3
19  1022  15  0    0  2
20  1023  16  1    1  0
21  1024  18  1    3  4
22  1025  18  1    0  1
23  1026  16  1    0  3
24  1027  16  0    0  1
25  1028  16  1    0  3
26  1029  18  0    0  0


In [24]:
read_csv_6 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv",names=["col1","col2","col3","col4","col5"])  #can give header names in a file 
print(read_csv_6)

         col1 col2    col3       col4               col5
0   StudentID  Age  Gender  Ethnicity  ParentalEducation
1        1001   17       1          0                  2
2        1002   18       0          0                  1
3        1003   15       0          2                  3
4        1004   17       1          0                  3
5        1005   17       1          0                  2
6        1006   18       0          0                  1
7        1007   15       0          1                  1
8        1008   15       1          1                  4
9        1009   17       0          0                  0
10       1010   16       1          0                  1
11       1011   17       0          0                  1
12       1012   17       0          0                  1
13       1013   17       0          1                  1
14       1014   17       0          1                  2
15       1015   18       1          0                  1
16       1016   15       0     

In [26]:
read_csv_7 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", dtype={"Age":"float"}) #convert age column to float
print(read_csv_7)

    StudentID   Age  Gender  Ethnicity  ParentalEducation
0        1001  17.0       1          0                  2
1        1002  18.0       0          0                  1
2        1003  15.0       0          2                  3
3        1004  17.0       1          0                  3
4        1005  17.0       1          0                  2
5        1006  18.0       0          0                  1
6        1007  15.0       0          1                  1
7        1008  15.0       1          1                  4
8        1009  17.0       0          0                  0
9        1010  16.0       1          0                  1
10       1011  17.0       0          0                  1
11       1012  17.0       0          0                  1
12       1013  17.0       0          1                  1
13       1014  17.0       0          1                  2
14       1015  18.0       1          0                  1
15       1016  15.0       0          0                  2
16       1017 

In [ ]:
import pandas as pd 
dic = {"A":[1,2,3], "B":[4,5,6], "C":[7,8,9]}
df = pd.DataFrame(dic, index=["a", "b", "c"])
print(df)
print(df.loc["b"])   # using loc we can access rows using given index./ if not  index changed then we can give integer position also
print(df.iloc[2])  # using iloc we can access rows using integer position.

csv = df.to_csv("practice.csv", index=False) 
read = pd.read_csv("practice.csv")
print(read)

   A  B  C
a  1  4  7
b  2  5  8
c  3  6  9
A    2
B    5
C    8
Name: b, dtype: int64
A    3
B    6
C    9
Name: c, dtype: int64
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


<h1>Pandas Function

In [29]:
import pandas as pd
csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv")
print(csv)

    StudentID  Age  Gender  Ethnicity  ParentalEducation
0        1001   17       1          0                  2
1        1002   18       0          0                  1
2        1003   15       0          2                  3
3        1004   17       1          0                  3
4        1005   17       1          0                  2
5        1006   18       0          0                  1
6        1007   15       0          1                  1
7        1008   15       1          1                  4
8        1009   17       0          0                  0
9        1010   16       1          0                  1
10       1011   17       0          0                  1
11       1012   17       0          0                  1
12       1013   17       0          1                  1
13       1014   17       0          1                  2


In [33]:
csv.index #start and stop index


RangeIndex(start=0, stop=14, step=1)

In [34]:
csv.columns #colums names


Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation'], dtype='object')

In [36]:
csv.describe() #gives function to int value only

StudentID        Age     Gender  Ethnicity  ParentalEducation
count    14.0000  14.000000  14.000000  14.000000          14.000000
mean   1007.5000  16.642857   0.357143   0.428571           1.642857
std       4.1833   1.008208   0.497245   0.646206           1.081818
min    1001.0000  15.000000   0.000000   0.000000           0.000000
25%    1004.2500  16.250000   0.000000   0.000000           1.000000
50%    1007.5000  17.000000   0.000000   0.000000           1.000000
75%    1010.7500  17.000000   1.000000   1.000000           2.000000
max    1014.0000  18.000000   1.000000   2.000000           4.000000

In [38]:
csv.head(2) #get first 2 rows , bydefault gives 5 rows

StudentID  Age  Gender  Ethnicity  ParentalEducation
0       1001   17       1          0                  2
1       1002   18       0          0                  1

In [41]:
csv.tail() #get last 5 rows

StudentID  Age  Gender  Ethnicity  ParentalEducation
9        1010   16       1          0                  1
10       1011   17       0          0                  1
11       1012   17       0          0                  1
12       1013   17       0          1                  1
13       1014   17       0          1                  2

In [52]:
csv[1:6] #slicing to get specific data
# csv[12:5:-1] #revrese

StudentID  Age  Gender  Ethnicity  ParentalEducation
1       1002   18       0          0                  1
2       1003   15       0          2                  3
3       1004   17       1          0                  3
4       1005   17       1          0                  2
5       1006   18       0          0                  1

In [53]:
csv.index.array  # convert index to array

<NumpyExtensionArray>
[ np.int64(0),  np.int64(1),  np.int64(2),  np.int64(3),  np.int64(4),
  np.int64(5),  np.int64(6),  np.int64(7),  np.int64(8),  np.int64(9),
 np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
Length: 14, dtype: int64

In [59]:
import numpy as np
# csv.to_numpy  # convert dataframe to numpy array
v = np.asarray(csv)
print(v)

[[1001   17    1    0    2]
 [1002   18    0    0    1]
 [1003   15    0    2    3]
 [1004   17    1    0    3]
 [1005   17    1    0    2]
 [1006   18    0    0    1]
 [1007   15    0    1    1]
 [1008   15    1    1    4]
 [1009   17    0    0    0]
 [1010   16    1    0    1]
 [1011   17    0    0    1]
 [1012   17    0    0    1]
 [1013   17    0    1    1]
 [1014   17    0    1    2]]


In [63]:
csv.sort_index(ascending=False,axis=0) #sort data in decending order at axis 0

StudentID  Age  Gender  Ethnicity  ParentalEducation
13       1014   17       0          1                  2
12       1013   17       0          1                  1
11       1012   17       0          0                  1
10       1011   17       0          0                  1
9        1010   16       1          0                  1
8        1009   17       0          0                  0
7        1008   15       1          1                  4
6        1007   15       0          1                  1
5        1006   18       0          0                  1
4        1005   17       1          0                  2
3        1004   17       1          0                  3
2        1003   15       0          2                  3
1        1002   18       0          0                  1
0        1001   17       1          0                  2

In [72]:
csv.loc[0,"Gender"] = "Male/Female"  #change specific element in dataframe,,,  loc[row, column]="changes"
print(csv)

    StudentID  Age       Gender  Ethnicity  ParentalEducation
0        1001  Age  Male/Female          0                  2
1        1002   18            0          0                  1
2        1003  Age            0          2                  3
3        1004   17            1          0                  3
4        1005   17            1          0                  2
5        1006   18            0          0                  1
6        1007   15            0          1                  1
7        1008   15            1          1                  4
8        1009   17            0          0                  0
9        1010   16            1          0                  1
10       1011   17            0          0                  1
11       1012   17            0          0                  1
12       1013   17            0          1                  1
13       1014   17            0          1                  2


In [79]:
csv.loc[[4,5],["Age","Gender"]] #get rows and columns only

Age Gender
4  17      1
5  18      0

In [83]:
csv.loc[[5, 6]]  #get full rows

StudentID Age Gender  Ethnicity  ParentalEducation
5       1006  18      0          0                  1
6       1007  15      0          1                  1

In [87]:
csv.iloc[0, 2]  #to get perticulat element give rows number and column number

'Male/Female'

In [92]:
csv.drop("Ethnicity",axis=1) #drop column

StudentID  Age       Gender  ParentalEducation
0        1001  Age  Male/Female                  2
1        1002   18            0                  1
2        1003  Age            0                  3
3        1004   17            1                  3
4        1005   17            1                  2
5        1006   18            0                  1
6        1007   15            0                  1
7        1008   15            1                  4
8        1009   17            0                  0
9        1010   16            1                  1
10       1011   17            0                  1
11       1012   17            0                  1
12       1013   17            0                  1
13       1014   17            0                  2