<h1>Pandas: Series</h1>

In [1]:
import pandas as pd

x = [3,4,5,6]
ser = pd.Series(x)
index = pd.Series(x, index=['a','b','c','d'])      #to change index of table by default it's 0-->n
datatype = pd.Series(x, index=['a','b','c','d'], dtype='float')     #convert to float 
name = pd.Series(x, index=['a','b','c','d'], dtype='float', name ='python')    # give specific name to dataset

print(ser)
print(index)
print(datatype)
print(name)

print(ser[2])        #to get element of array
print(index['b'])   # we can access the elements using index of table

0    3
1    4
2    5
3    6
dtype: int64
a    3
b    4
c    5
d    6
dtype: int64
a    3.0
b    4.0
c    5.0
d    6.0
dtype: float64
a    3.0
b    4.0
c    5.0
d    6.0
Name: python, dtype: float64
5
4


In [2]:
dic = {"name":['python','c','c++','java'], "por":[12,13,14,15], "rank":[1,4,3,2]}
var1 = pd.Series(dic) 
var1

name    [python, c, c++, java]
por           [12, 13, 14, 15]
rank              [1, 4, 3, 2]
dtype: object

In [3]:
import pandas as pd
s = pd.Series(12)            # create series of 12 at 0th position 
m = pd.Series(12, index = [1,2,3,4,5,6,7,8]) #create series for 12 at given index position
print(s)
print(m)

0    12
dtype: int64
1    12
2    12
3    12
4    12
5    12
6    12
7    12
8    12
dtype: int64


In [4]:
#if we need to add two Series data it will add likw below.but it will add up to same
#index which is present in both series. (size should be same ) else it print NaN(not a number)
#in numpy if we did this we got broadcast error. but pandas will support this. 

m = pd.Series(12, index = [1,2,3,4,5,6,7,8])
n = pd.Series(12, index = [1,2,3,4])
print((m + n))

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64


<h1>Pandas: DataFrame

In [5]:
import pandas as pd
list1 = [1,2,3,4,5,6]
var = pd.DataFrame(list1)
print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>


In [6]:
dictionary = {"a":[1,2,3,14,5], "s":[1,2,3,4,5],"d":[1,2,3,4,5],1:[1,2,3,4,5]}
var1 = pd.DataFrame(dictionary)
print(var1)

print(var1["a"][3])  #get specific element from DataFrame

var2 = pd.DataFrame(dictionary, columns=["a"]) #print only column a 
print(var2)

    a  s  d  1
0   1  1  1  1
1   2  2  2  2
2   3  3  3  3
3  14  4  4  4
4   5  5  5  5
14
    a
0   1
1   2
2   3
3  14
4   5


In [7]:
list_1 = [ [1,2,3,4,5], [11,12,13,14,15] ]
v = pd.DataFrame(list_1)
v

0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [8]:
sr = {
    "s":pd.Series([1,2,3,4]), 
    "r":pd.Series([5,6,7,8])}
n = pd.DataFrame(sr)
print(n)

   s  r
0  1  5
1  2  6
2  3  7
3  4  8


In [9]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [10]:
print(myvar.loc[0])     # to get rows from DataFrame use loc[] function, it will return a Series

calories    420
duration     50
Name: 0, dtype: int64


In [11]:
print(myvar.loc[[0 , 1]])   ## to get rows from DataFrame use loc[[]] function with [] , it will return a DataFrame

   calories  duration
0       420        50
1       380        40


<h1>Pandas: Arithmetic operation

In [12]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8


In [13]:
import pandas as pd 
var = pd.DataFrame(
    {
        "A":[1,2,3,4], "B":[5,6,7,8]
    })
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8


In [14]:
var["C"] = var["A"] + var["B"]    #addition of both column
print(var)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12


In [15]:
var["D"] = var["A"] - var["B"]    #substraction of both column
print(var)

   A  B   C  D
0  1  5   6 -4
1  2  6   8 -4
2  3  7  10 -4
3  4  8  12 -4


In [16]:
var1 = pd.DataFrame({"A":[10,20,30,40], "B":[50,60,70,80]})
print(var1)



    A   B
0  10  50
1  20  60
2  30  70
3  40  80


In [17]:
var1["python"] = var1["A"] <= 20     #create new column named as "python" and check if data in column "A" is less than 20
print(var1)

    A   B  python
0  10  50    True
1  20  60    True
2  30  70   False
3  40  80   False


In [18]:
var1["python_1"] = var1["B"] >= 60     #create new column named as "python_1" and check if data in column "B" is greater than 60
print(var1)

    A   B  python  python_1
0  10  50    True     False
1  20  60    True      True
2  30  70   False      True
3  40  80   False      True


<h1>Insert 

In [19]:
import pandas as pd 
var = pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[6,7,8,9,10]
})
print(var)

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10


In [20]:

var.insert(1,"python", [11,12,13,14.15])  #insert given data at 1th position in dataframe with column name as python.
print(var)

ValueError: Length of values (4) does not match length of index (5)

In [ ]:
var["python_1"] = var["A"][0:3]    #copy 0 to 3 data from column "A" and  add in a python-1 column.
print(var)

NameError: name 'var' is not defined

<h1>Delete

In [ ]:
import pandas as pd 
data = pd.DataFrame({
    "A":[1,2,3,4,5],
    "B":[6,7,8,9,10],
    "C":[11,12,13,14,15],
    "E":[20,21,22,23,24]
})
print(data)

   A   B   C   E
0  1   6  11  20
1  2   7  12  21
2  3   8  13  22
3  4   9  14  23
4  5  10  15  24


In [ ]:
pop = data.pop("B") #for pop we use () with column to be delete
print(pop)

0     6
1     7
2     8
3     9
4    10
Name: B, dtype: int64


In [ ]:
print(data)

   A   C   E
0  1  11  20
1  2  12  21
2  3  13  22
3  4  14  23
4  5  15  24


In [ ]:
del data["E"]   #for delete we use [] with column to be delete

In [ ]:
print(data)

   A   C
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15


<h1> Create CSV file

In [ ]:
import pandas as pd
dic = {"a":[1,2,3,4,5], "b":[1,2,3,4,5],"c":[1,2,3,4,5]}
frame = pd.DataFrame(dic)
print(frame)

frame.to_csv("Test.csv") #create csv file named Test.csv
frame.to_csv("Test_new.csv", index = False) #remove index
frame.to_csv("Test_new1.csv", index= False, header=[1,2,3]) #rename column name using header


   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5


<h1>Read CSV 


In [ ]:
import pandas as pd 
read_csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Test_new.csv")
print(read_csv)


   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5


In [ ]:
import pandas as pd 
read_csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Test_new.csv",nrows=2)  # to get no of rows then use 'nrows'
print(read_csv)

read_csv_1 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", usecols=["Age"])  # to get perticuler column in csv file use "usecols=["column_name"]"
print(read_csv_1)

read_csv_2 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", usecols=[2])  # to get perticuler column in csv file we can give interger position of column also.
print(read_csv_2)


   a  b  c
0  1  1  1
1  2  2  2
     Age
0     17
1     18
2     15
3     17
4     17
..   ...
143   18
144   18
145   17
146   17
147   17

[148 rows x 1 columns]
     Gender
0         1
1         0
2         0
3         1
4         1
..      ...
143       0
144       0
145       1
146       1
147       0

[148 rows x 1 columns]


In [ ]:
read_csv_3 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", skiprows=[0])  #using this we can skip rows in a csv file
print(read_csv_3)

     1001  17  1  0  2  19.833722807854713   7  1.1  2.1  0.1  0.2  1.2  0.3  \
0    1002  18  0  0  1           15.408756   0    0    1    0    0    0    0   
1    1003  15  0  2  3            4.210570  26    0    2    0    0    0    0   
2    1004  17  1  0  3           10.028829  14    0    3    1    0    0    0   
3    1005  17  1  0  2            4.672495  17    1    3    0    0    0    0   
4    1006  18  0  0  1            8.191219   0    0    1    1    0    0    0   
..    ...  .. .. .. ..                 ...  ..  ...  ...  ...  ...  ...  ...   
142  1144  18  0  2  1           18.978324  16    0    2    1    0    1    0   
143  1145  18  0  2  2            4.919995   7    1    2    1    1    0    0   
144  1146  17  1  0  3           10.641736   9    0    3    1    0    0    0   
145  1147  17  1  2  2            9.647124   1    1    2    1    0    0    1   
146  1148  17  0  2  1           14.057329  11    0    3    0    1    0    0   

     2.929195591667681  2.0  
0        

In [21]:
read_csv_4 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv",index_col=["Age"])  #using this we can use Age column as a index in a file .rather than using original index.
print(read_csv_4)

     StudentID  Gender  Ethnicity  ParentalEducation
Age                                                 
17        1001       1          0                  2
18        1002       0          0                  1
15        1003       0          2                  3
17        1004       1          0                  3
17        1005       1          0                  2
18        1006       0          0                  1
15        1007       0          1                  1
15        1008       1          1                  4
17        1009       0          0                  0
16        1010       1          0                  1
17        1011       0          0                  1
17        1012       0          0                  1
17        1013       0          1                  1
17        1014       0          1                  2
18        1015       1          0                  1
15        1016       0          0                  2
18        1017       0          3             

In [25]:
import pandas as pd
read_csv_5 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv",header=2)  #using this we can use second column as a header in a file.
print(read_csv_5)

    1002  18  0  0.1  1
0   1003  15  0    2  3
1   1004  17  1    0  3
2   1005  17  1    0  2
3   1006  18  0    0  1
4   1007  15  0    1  1
5   1008  15  1    1  4
6   1009  17  0    0  0
7   1010  16  1    0  1
8   1011  17  0    0  1
9   1012  17  0    0  1
10  1013  17  0    1  1
11  1014  17  0    1  2
12  1015  18  1    0  1
13  1016  15  0    0  2
14  1017  18  0    3  1
15  1018  18  1    0  0
16  1019  18  0    1  3
17  1020  17  0    0  1
18  1021  16  1    0  3
19  1022  15  0    0  2
20  1023  16  1    1  0
21  1024  18  1    3  4
22  1025  18  1    0  1
23  1026  16  1    0  3
24  1027  16  0    0  1
25  1028  16  1    0  3
26  1029  18  0    0  0


In [24]:
read_csv_6 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv",names=["col1","col2","col3","col4","col5"])  #can give header names in a file 
print(read_csv_6)

         col1 col2    col3       col4               col5
0   StudentID  Age  Gender  Ethnicity  ParentalEducation
1        1001   17       1          0                  2
2        1002   18       0          0                  1
3        1003   15       0          2                  3
4        1004   17       1          0                  3
5        1005   17       1          0                  2
6        1006   18       0          0                  1
7        1007   15       0          1                  1
8        1008   15       1          1                  4
9        1009   17       0          0                  0
10       1010   16       1          0                  1
11       1011   17       0          0                  1
12       1012   17       0          0                  1
13       1013   17       0          1                  1
14       1014   17       0          1                  2
15       1015   18       1          0                  1
16       1016   15       0     

In [26]:
read_csv_7 = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv", dtype={"Age":"float"}) #convert age column to float
print(read_csv_7)

    StudentID   Age  Gender  Ethnicity  ParentalEducation
0        1001  17.0       1          0                  2
1        1002  18.0       0          0                  1
2        1003  15.0       0          2                  3
3        1004  17.0       1          0                  3
4        1005  17.0       1          0                  2
5        1006  18.0       0          0                  1
6        1007  15.0       0          1                  1
7        1008  15.0       1          1                  4
8        1009  17.0       0          0                  0
9        1010  16.0       1          0                  1
10       1011  17.0       0          0                  1
11       1012  17.0       0          0                  1
12       1013  17.0       0          1                  1
13       1014  17.0       0          1                  2
14       1015  18.0       1          0                  1
15       1016  15.0       0          0                  2
16       1017 

In [ ]:
import pandas as pd 
dic = {"A":[1,2,3], "B":[4,5,6], "C":[7,8,9]}
df = pd.DataFrame(dic, index=["a", "b", "c"])
print(df)
print(df.loc["b"])   # using loc we can access rows using given index./ if not  index changed then we can give integer position also
print(df.iloc[2])  # using iloc we can access rows using integer position.

csv = df.to_csv("practice.csv", index=False) 
read = pd.read_csv("practice.csv")
print(read)

   A  B  C
a  1  4  7
b  2  5  8
c  3  6  9
A    2
B    5
C    8
Name: b, dtype: int64
A    3
B    6
C    9
Name: c, dtype: int64
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


<h1>Pandas Function

In [29]:
import pandas as pd
csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv")
print(csv)

    StudentID  Age  Gender  Ethnicity  ParentalEducation
0        1001   17       1          0                  2
1        1002   18       0          0                  1
2        1003   15       0          2                  3
3        1004   17       1          0                  3
4        1005   17       1          0                  2
5        1006   18       0          0                  1
6        1007   15       0          1                  1
7        1008   15       1          1                  4
8        1009   17       0          0                  0
9        1010   16       1          0                  1
10       1011   17       0          0                  1
11       1012   17       0          0                  1
12       1013   17       0          1                  1
13       1014   17       0          1                  2


In [33]:
csv.index #start and stop index


RangeIndex(start=0, stop=14, step=1)

In [34]:
csv.columns #colums names


Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation'], dtype='object')

In [36]:
csv.describe() #gives function to int value only

StudentID        Age     Gender  Ethnicity  ParentalEducation
count    14.0000  14.000000  14.000000  14.000000          14.000000
mean   1007.5000  16.642857   0.357143   0.428571           1.642857
std       4.1833   1.008208   0.497245   0.646206           1.081818
min    1001.0000  15.000000   0.000000   0.000000           0.000000
25%    1004.2500  16.250000   0.000000   0.000000           1.000000
50%    1007.5000  17.000000   0.000000   0.000000           1.000000
75%    1010.7500  17.000000   1.000000   1.000000           2.000000
max    1014.0000  18.000000   1.000000   2.000000           4.000000

In [38]:
csv.head(2) #get first 2 rows , bydefault gives 5 rows

StudentID  Age  Gender  Ethnicity  ParentalEducation
0       1001   17       1          0                  2
1       1002   18       0          0                  1

In [41]:
csv.tail() #get last 5 rows

StudentID  Age  Gender  Ethnicity  ParentalEducation
9        1010   16       1          0                  1
10       1011   17       0          0                  1
11       1012   17       0          0                  1
12       1013   17       0          1                  1
13       1014   17       0          1                  2

In [52]:
csv[1:6] #slicing to get specific data
# csv[12:5:-1] #revrese

StudentID  Age  Gender  Ethnicity  ParentalEducation
1       1002   18       0          0                  1
2       1003   15       0          2                  3
3       1004   17       1          0                  3
4       1005   17       1          0                  2
5       1006   18       0          0                  1

In [53]:
csv.index.array  # convert index to array

<NumpyExtensionArray>
[ np.int64(0),  np.int64(1),  np.int64(2),  np.int64(3),  np.int64(4),
  np.int64(5),  np.int64(6),  np.int64(7),  np.int64(8),  np.int64(9),
 np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
Length: 14, dtype: int64

In [59]:
import numpy as np
# csv.to_numpy  # convert dataframe to numpy array
v = np.asarray(csv)
print(v)

[[1001   17    1    0    2]
 [1002   18    0    0    1]
 [1003   15    0    2    3]
 [1004   17    1    0    3]
 [1005   17    1    0    2]
 [1006   18    0    0    1]
 [1007   15    0    1    1]
 [1008   15    1    1    4]
 [1009   17    0    0    0]
 [1010   16    1    0    1]
 [1011   17    0    0    1]
 [1012   17    0    0    1]
 [1013   17    0    1    1]
 [1014   17    0    1    2]]


In [63]:
csv.sort_index(ascending=False,axis=0) #sort data in decending order at axis 0

StudentID  Age  Gender  Ethnicity  ParentalEducation
13       1014   17       0          1                  2
12       1013   17       0          1                  1
11       1012   17       0          0                  1
10       1011   17       0          0                  1
9        1010   16       1          0                  1
8        1009   17       0          0                  0
7        1008   15       1          1                  4
6        1007   15       0          1                  1
5        1006   18       0          0                  1
4        1005   17       1          0                  2
3        1004   17       1          0                  3
2        1003   15       0          2                  3
1        1002   18       0          0                  1
0        1001   17       1          0                  2

In [72]:
csv.loc[0,"Gender"] = "Male/Female"  #change specific element in dataframe,,,  loc[row, column]="changes"
print(csv)

    StudentID  Age       Gender  Ethnicity  ParentalEducation
0        1001  Age  Male/Female          0                  2
1        1002   18            0          0                  1
2        1003  Age            0          2                  3
3        1004   17            1          0                  3
4        1005   17            1          0                  2
5        1006   18            0          0                  1
6        1007   15            0          1                  1
7        1008   15            1          1                  4
8        1009   17            0          0                  0
9        1010   16            1          0                  1
10       1011   17            0          0                  1
11       1012   17            0          0                  1
12       1013   17            0          1                  1
13       1014   17            0          1                  2


In [79]:
csv.loc[[4,5],["Age","Gender"]] #get rows and columns only

Age Gender
4  17      1
5  18      0

In [83]:
csv.loc[[5, 6]]  #get full rows

StudentID Age Gender  Ethnicity  ParentalEducation
5       1006  18      0          0                  1
6       1007  15      0          1                  1

In [87]:
csv.iloc[0, 2]  #to get perticulat element give rows number and column number

'Male/Female'

In [92]:
csv.drop("Ethnicity",axis=1) #drop column

StudentID  Age       Gender  ParentalEducation
0        1001  Age  Male/Female                  2
1        1002   18            0                  1
2        1003  Age            0                  3
3        1004   17            1                  3
4        1005   17            1                  2
5        1006   18            0                  1
6        1007   15            0                  1
7        1008   15            1                  4
8        1009   17            0                  0
9        1010   16            1                  1
10       1011   17            0                  1
11       1012   17            0                  1
12       1013   17            0                  1
13       1014   17            0                  2

<h1>dropna fillna

In [98]:
import pandas as pd
csv = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\data.csv")
print(csv)
# print(csv.to_string())  # to_string()   for print whole dataset

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [103]:
'''One way to deal with empty cells is to remove rows that contain empty cells.
This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.'''

new_csv = csv.dropna()
print(new_csv)         #dropna return new dataframe , if u want to change original dataframe, use "inplace = True"

new_csv1 = csv.dropna(inplace=True) # can give axis also 0 or 1
print(new_csv1)

new_csv2 = csv.dropna(subset=["Calories"]) #it will drop NaN value from Calories column. 
print(new_csv2)

new_csv3 = csv.dropna(thresh= 1) # we can change value
print(new_csv3)     # the column which has only one NaN value they can thresh/drop. if 2 then thresh 2 NaN value column.
 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]
None
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       1

In [107]:
#fillna
import pandas as pd
fill = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv")
print(fill)

   StudentID  Age  Gender  Ethnicity  ParentalEducation
0       1001   17       1        NaN                NaN
1       1002   18       0        0.0                1.0
2       1003   15       0        2.0                3.0
3       1004   17       1        0.0                3.0
4       1005   17       1        0.0                2.0
5       1006   18       0        0.0                1.0
6       1007   15       0        1.0                1.0
7              15       1        4.0                NaN
8       1009   17       0        0.0                0.0
9       1010   16       1        0.0                1.0
10      1011   17       0        0.0                1.0
11      1012   17       0        0.0                1.0
12      1013   17       0        1.0                1.0
13      1014   17       0        1.0                2.0


In [110]:
var = fill.fillna("Vinod") # fill  entire NaN value in dataframe by 'Vinod'
print(var)

   StudentID  Age  Gender Ethnicity ParentalEducation
0       1001   17       1     Vinod             Vinod
1       1002   18       0       0.0               1.0
2       1003   15       0       2.0               3.0
3       1004   17       1       0.0               3.0
4       1005   17       1       0.0               2.0
5       1006   18       0       0.0               1.0
6       1007   15       0       1.0               1.0
7              15       1       4.0             Vinod
8       1009   17       0       0.0               0.0
9       1010   16       1       0.0               1.0
10      1011   17       0       0.0               1.0
11      1012   17       0       0.0               1.0
12      1013   17       0       1.0               1.0
13      1014   17       0       1.0               2.0


In [4]:
import pandas as pd
fill = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\Student.csv")
var2 = fill.fillna({"StudentID":"python", "Ethnicity":"Java", "ParentalEducation":"pandas"}) #likewise we can replace NaN value in perticular column with perticular name.
print(var2)
# fill["StudentID"].fillna(130, inplace = True) #to change value for StudentID column only with 130

    StudentID  Age  Gender Ethnicity ParentalEducation
0        1001   17       1      Java            pandas
1        1002   18       0       0.0               1.0
2        1003   15       0       2.0               3.0
3        1004   17       1       0.0               3.0
4        1005   17       1       0.0               2.0
5        1006   18       0       0.0               1.0
6        1007   15       0       1.0               1.0
7        1008   15       1       4.0            pandas
8        1009   17       0       0.0               0.0
9        1010   16       1       0.0               1.0
10       1011   17       0       0.0               1.0
11       1012   17       0       0.0               1.0
12       1013   17       0       1.0               1.0
13       1014   17       0       1.0               2.0


In [117]:
fill.fillna(method="ffill") #forward fill,  next element added at NaN value.
fill.fillna(method="bfill")#backward fill,previous element added at NaN value 

C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_18000\776186753.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  fill.fillna(method="ffill") #forward fill,  next element added at NaN value.
C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_18000\776186753.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  fill.fillna(method="bfill")#backward fill,previous element added at NaN value


StudentID  Age  Gender  Ethnicity  ParentalEducation
0       1001   17       1        0.0                1.0
1       1002   18       0        0.0                1.0
2       1003   15       0        2.0                3.0
3       1004   17       1        0.0                3.0
4       1005   17       1        0.0                2.0
5       1006   18       0        0.0                1.0
6       1007   15       0        1.0                1.0
7              15       1        4.0                0.0
8       1009   17       0        0.0                0.0
9       1010   16       1        0.0                1.0
10      1011   17       0        0.0                1.0
11      1012   17       0        0.0                1.0
12      1013   17       0        1.0                1.0
13      1014   17       0        1.0                2.0

<h1>Replace

In [1]:
import pandas as pd
df  = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\cereal.csv")
print(df)


                         name mfr type  calories  protein
0                   100% Bran   N    C        70        4
1           100% Natural Bran   Q    C       120        3
2                    All-Bran   K    C        70        4
3   All-Bran with Extra Fiber   K    C        50        4
4              Almond Delight   R    C       110        2
5     Apple Cinnamon Cheerios   G    C       110        2
6                 Apple Jacks   K    C       110        2
7                     Basic 4   G    C       130        3
8                   Bran Chex   R    C        90        2
9                 Bran Flakes   P    C        90        3
10               Cap'n'Crunch   Q    C       120        1
11                   Cheerios   G    C       110        6
12      Cinnamon Toast Crunch   G    C       120        1
13                   Clusters   G    C       110        3
14                Cocoa Puffs   G    C       110        1
15                  Corn Chex   R    C       110        2
16            

In [2]:
df.replace(to_replace="C",value="O+")   #using this we can replace all values of "C" to "O+" in whole dataframe.


name mfr type  calories  protein
0                   100% Bran   N   O+        70        4
1           100% Natural Bran   Q   O+       120        3
2                    All-Bran   K   O+        70        4
3   All-Bran with Extra Fiber   K   O+        50        4
4              Almond Delight   R   O+       110        2
5     Apple Cinnamon Cheerios   G   O+       110        2
6                 Apple Jacks   K   O+       110        2
7                     Basic 4   G   O+       130        3
8                   Bran Chex   R   O+        90        2
9                 Bran Flakes   P   O+        90        3
10               Cap'n'Crunch   Q   O+       120        1
11                   Cheerios   G   O+       110        6
12      Cinnamon Toast Crunch   G   O+       120        1
13                   Clusters   G   O+       110        3
14                Cocoa Puffs   G   O+       110        1
15                  Corn Chex   R   O+       110        2
16                Corn Flakes   K   O+       100        2
17                  Corn Pops   K   O+       110        1
18              Count Chocula   G   O+       110        1
19         Cracklin' Oat Bran   K   O+       110        3
20     Cream of Wheat (Quick)   N    H       100        3

In [10]:
df. replace({"name":'[A - Z]'}, 22, regex=True)  #using dict we can replace [A - Z] letters from column name to 22, using regular expression.

name mfr type  calories  protein
0             22   N    C        70        4
1             22   Q    C       120        3
2             22   K    C        70        4
3             22   K    C        50        4
4             22   R    C       110        2
5             22   G    C       110        2
6             22   K    C       110        2
7             22   G    C       130        3
8             22   R    C        90        2
9             22   P    C        90        3
10  Cap'n'Crunch   Q    C       120        1
11      Cheerios   G    C       110        6
12            22   G    C       120        1
13      Clusters   G    C       110        3
14            22   G    C       110        1
15            22   R    C       110        2
16            22   K    C       100        2
17            22   K    C       110        1
18            22   G    C       110        1
19            22   K    C       110        3
20            22   N    H       100        3

In [12]:
df.replace(1, method="bfill")   #using this all 1 in df replaced by backward fill in whole df
                                # we can use ffill for forward replace

# df.replace(1, method="bfill",limit=2) #by passing limit we can replace data up to seted limit. not whole df.

C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_12252\704622754.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(1, method="bfill")


name mfr type  calories  protein
0                   100% Bran   N    C        70        4
1           100% Natural Bran   Q    C       120        3
2                    All-Bran   K    C        70        4
3   All-Bran with Extra Fiber   K    C        50        4
4              Almond Delight   R    C       110        2
5     Apple Cinnamon Cheerios   G    C       110        2
6                 Apple Jacks   K    C       110        2
7                     Basic 4   G    C       130        3
8                   Bran Chex   R    C        90        2
9                 Bran Flakes   P    C        90        3
10               Cap'n'Crunch   Q    C       120        6
11                   Cheerios   G    C       110        6
12      Cinnamon Toast Crunch   G    C       120        3
13                   Clusters   G    C       110        3
14                Cocoa Puffs   G    C       110        2
15                  Corn Chex   R    C       110        2
16                Corn Flakes   K    C       100        2
17                  Corn Pops   K    C       110        3
18              Count Chocula   G    C       110        3
19         Cracklin' Oat Bran   K    C       110        3
20     Cream of Wheat (Quick)   N    H       100        3

<h1>interpolate / infer_objects


In [17]:
import pandas as pd
df = pd.read_csv("C:\\Users\\VSARWADE\\Desktop\\Pandas\\cereal.csv")
print(df)

                         name mfr type  calories  protein
0                   100% Bran   N    C      70.0        4
1           100% Natural Bran   Q    C     120.0        3
2                    All-Bran   K    C      70.0        4
3   All-Bran with Extra Fiber   K    C      50.0        4
4              Almond Delight   R  NaN     110.0        2
5     Apple Cinnamon Cheerios   G    C     110.0        2
6                 Apple Jacks   K    C     110.0        2
7                     Basic 4   G    C       NaN        3
8                   Bran Chex   R    C      90.0        2
9                 Bran Flakes   P    C      90.0        3
10               Cap'n'Crunch   Q    C     120.0        1
11                   Cheerios   G    C     110.0        6
12      Cinnamon Toast Crunch   G    C     120.0        1
13                   Clusters   G    C     110.0        3
14                Cocoa Puffs   G    C     110.0        1
15                  Corn Chex   R    C     110.0        2
16            

In [21]:
'''interpolate will autometically replce NaN value from dataframe to a linear values in df.
but now interpolate will not support for latest version so we can use infer_objects insted.
this will only replace for int value. not for string. '''
df.interpolate()
# df.infer_objects()

C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_12252\2219442395.py:4: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()


name mfr type  calories  protein
0                   100% Bran   N    C      70.0        4
1           100% Natural Bran   Q    C     120.0        3
2                    All-Bran   K    C      70.0        4
3   All-Bran with Extra Fiber   K    C      50.0        4
4              Almond Delight   R  NaN     110.0        2
5     Apple Cinnamon Cheerios   G    C     110.0        2
6                 Apple Jacks   K    C     110.0        2
7                     Basic 4   G    C     100.0        3
8                   Bran Chex   R    C      90.0        2
9                 Bran Flakes   P    C      90.0        3
10               Cap'n'Crunch   Q    C     120.0        1
11                   Cheerios   G    C     110.0        6
12      Cinnamon Toast Crunch   G    C     120.0        1
13                   Clusters   G    C     110.0        3
14                Cocoa Puffs   G    C     110.0        1
15                  Corn Chex   R    C     110.0        2
16                Corn Flakes   K    C     100.0        2
17                  Corn Pops   K    C     110.0        1
18              Count Chocula   G    C     110.0        1
19         Cracklin' Oat Bran   K    C     110.0        3
20     Cream of Wheat (Quick)   N    H     100.0        3

In [23]:
#suppose we have multiple NaN value in column and you need to replace only 2 value from backword side (down -> up side) then use direction backword.
df.interpolate(limit_direction="forward", limit= 2)
df.interpolate(limit_direction="backward", limit= 2)
df.interpolate(limit_direction="both", limit= 2)  # fill data from both side.

C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_12252\2944377687.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction="forward", limit= 2)
C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_12252\2944377687.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction="backward", limit= 2)
C:\Users\VSARWADE\AppData\Local\Temp\ipykernel_12252\2944377687.py:4: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction="both", limit= 2)  # fill data from both side.


name mfr type  calories  protein
0                   100% Bran   N    C      70.0        4
1           100% Natural Bran   Q    C     120.0        3
2                    All-Bran   K    C      70.0        4
3   All-Bran with Extra Fiber   K    C      50.0        4
4              Almond Delight   R  NaN     110.0        2
5     Apple Cinnamon Cheerios   G    C     110.0        2
6                 Apple Jacks   K    C     110.0        2
7                     Basic 4   G    C     100.0        3
8                   Bran Chex   R    C      90.0        2
9                 Bran Flakes   P    C      90.0        3
10               Cap'n'Crunch   Q    C     120.0        1
11                   Cheerios   G    C     110.0        6
12      Cinnamon Toast Crunch   G    C     120.0        1
13                   Clusters   G    C     110.0        3
14                Cocoa Puffs   G    C     110.0        1
15                  Corn Chex   R    C     110.0        2
16                Corn Flakes   K    C     100.0        2
17                  Corn Pops   K    C     110.0        1
18              Count Chocula   G    C     110.0        1
19         Cracklin' Oat Bran   K    C     110.0        3
20     Cream of Wheat (Quick)   N    H     100.0        3

<h1>Merge and Concat DataFrames

In [46]:
import pandas as pd
var1 = pd.DataFrame({"A":[1,2,3,4], "B":[10,11,12,13]})
var2 = pd.DataFrame({"A":[1,2,3,4], "C":[20,21,22,23]})

pd.merge(var1, var2, on ="A")  # for merging we need to give 1 parameter which is common in both df.
                               #here A column is same for both df.

A   B   C
0  1  10  20
1  2  11  21
2  3  12  22
3  4  13  23

In [41]:
import pandas as pd
num1 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
num2 = pd.DataFrame({"A":[1,2,3,5], "C":[21,22,23,24]})

pd.merge(num1, num2, on="A") #here in num2 i changed 4 to 5 in "A". so now this column are not same.so it will merge up to 3 only

A   B   C
0  1  11  21
1  2  12  22
2  3  13  23

In [53]:
#if you want print whole df after changing element or you have missing value then we can pass how="" parameter.
# pd.merge(num1, num2, how="left") #it will check & merge from left side i.e. in num1 "A", and missing element in right side ie."C" printed as NaN
# pd.merge(num1, num2, how="right") #it will check & merge from right side i.e. in num2 "A", and missing element in left side ie."B" printed as NaN

pd.merge(num1, num2, how="outer") #it will print both side of data with missing values.


A     B     C
0  1  11.0  21.0
1  2  12.0  22.0
2  3  13.0  23.0
3  4  14.0   NaN
4  5   NaN  24.0

In [52]:
pd.merge(num1, num2, how="outer", indicator=True) #by passing indicator you check on which side data is present or not.

A     B     C      _merge
0  1  11.0  21.0        both
1  2  12.0  22.0        both
2  3  13.0  23.0        both
3  4  14.0   NaN   left_only
4  5   NaN  24.0  right_only

In [54]:
import pandas as pd
num3 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
num4 = pd.DataFrame({"A":[1,2,3,5], "B":[21,22,23,24]})

pd.merge(num3, num4, left_index=True, right_index=True) # if you have same column name but diff data. to print this type of data pass left_index and right_index in param.
                     #then only we can print same column name data.

A_x  B_x  A_y  B_y
0    1   11    1   21
1    2   12    2   22
2    3   13    3   23
3    4   14    5   24

<h1>concat

In [56]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,12,13,13])
pd.concat([sr1, sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    13
dtype: int64

In [58]:
p1 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
p2= pd.DataFrame({"A":[1,2,3,5], "B":[21,22,23,24]})
pd.concat([p1, p2]) # we can pass axix = 1 for colums wise concat

A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  5  24

In [70]:
p3 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
p4= pd.DataFrame({"A":[1,2], "B":[21,22]})
# pd.concat([p3, p4], axis=1) # in this case we dont have equal data in both df. if we want to print only available data without using NaN value use join param
pd.concat([p3, p4],axis=1, join="inner") # print only data thode present in both df. (intersection)

A   B  A   B
0  1  11  1  21
1  2  12  2  22

<h1>Group by

In [74]:
'''if you have random data and you need to do it serially. then we can use group by function which can group similar data. and return new df.'''
import pandas as pd
var1 = pd.DataFrame({"name":["a","b","c","d","a","b","a","b","a","c","c","d"],
                     "subject":[12,13,14,12,13,14,15,23,25,16,10,34],
                     "subject_2":[23,24,25,26,27,28,29,30,25,34,35,56]})

print(var1)

   name  subject  subject_2
0     a       12         23
1     b       13         24
2     c       14         25
3     d       12         26
4     a       13         27
5     b       14         28
6     a       15         29
7     b       23         30
8     a       25         25
9     c       16         34
10    c       10         35
11    d       34         56


In [89]:
var1_new = var1.groupby("name")  #it will gropu data in name column with same column name.
print(var1_new)
for i, j in var1_new: 
    print(i)
    print(j)
    print()

a
  name  subject  subject_2
0    a       12         23
4    a       13         27
6    a       15         29
8    a       25         25

b
  name  subject  subject_2
1    b       13         24
5    b       14         28
7    b       23         30

c
   name  subject  subject_2
2     c       14         25
9     c       16         34
10    c       10         35

d
   name  subject  subject_2
3     d       12         26
11    d       34         56



In [90]:

var1_new.get_group("a") # it will print only grop a

name  subject  subject_2
0    a       12         23
4    a       13         27
6    a       15         29
8    a       25         25

In [81]:
var1_new.min() # we can  find min of each group.

subject  subject_2
name                    
a          12         23
b          13         24
c          10         25
d          12         26

In [84]:
# var1_new.max()
var1_new.mean()

subject  subject_2
name                      
a     16.250000  26.000000
b     16.666667  27.333333
c     13.333333  31.333333
d     23.000000  41.000000

In [85]:
li = list(var1_new)   # we can convert it in to list also
print(li)

[('a',   name  subject  subject_2
0    a       12         23
4    a       13         27
6    a       15         29
8    a       25         25), ('b',   name  subject  subject_2
1    b       13         24
5    b       14         28
7    b       23         30), ('c',    name  subject  subject_2
2     c       14         25
9     c       16         34
10    c       10         35), ('d',    name  subject  subject_2
3     d       12         26
11    d       34         56)]


<h1>join and append

In [92]:
import pandas as pd
df = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,13]})
df2 = pd.DataFrame({"C":[10,20], "D":[11,22]})
df.join(df2)  # we can add how param as well to print specific data

A   B     C     D
0  1  11  10.0  11.0
1  2  12  20.0  22.0
2  3  13   NaN   NaN
3  4  13   NaN   NaN

In [94]:
df = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,13]})
df2 = pd.DataFrame({"C":[10,20], "B":[11,22]})     
# df.join(df2)     # due to same column name used for B it will raise an error .. to fix that we can use 'suffix' param
df.join(df2, lsuffix="_12", rsuffix="_12") #left suffix and right

A  B_12     C  B_12
0  1    11  10.0  11.0
1  2    12  20.0  22.0
2  3    13   NaN   NaN
3  4    13   NaN   NaN

<h1>append

In [97]:
import pandas as pd
df = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,13]})
df2 = pd.DataFrame({"C":[10,20], "D":[11,22]})

df.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

<h1>Melt function



In [102]:
import pandas as pd
var = pd.DataFrame({"day":[1,2,3,4,5,6], "eng":[10,12,13,14,15,16], "math":[43,22,56,43,66,77]})
print(var)
pd.melt(var)  # using melt we can reshape df in column wise



   day  eng  math
0    1   10    43
1    2   12    22
2    3   13    56
3    4   14    43
4    5   15    66
5    6   16    77


variable  value
0       day      1
1       day      2
2       day      3
3       day      4
4       day      5
5       day      6
6       eng     10
7       eng     12
8       eng     13
9       eng     14
10      eng     15
11      eng     16
12     math     43
13     math     22
14     math     56
15     math     43
16     math     66
17     math     77

In [101]:
pd.melt(var, id_vars=["day"])  #by passing id_vars param we can create perticuler column as a id. means this columns are first column in df.

day variable  value
0     1      eng     10
1     2      eng     12
2     3      eng     13
3     4      eng     14
4     5      eng     15
5     6      eng     16
6     1     math     43
7     2     math     22
8     3     math     56
9     4     math     43
10    5     math     66
11    6     math     77

In [103]:
#in above cell we can see all data is stored in variable column and value column. we can change this names also
pd.melt(var, id_vars=["day"], var_name="python", value_name="marks") 

day python  marks
0     1    eng     10
1     2    eng     12
2     3    eng     13
3     4    eng     14
4     5    eng     15
5     6    eng     16
6     1   math     43
7     2   math     22
8     3   math     56
9     4   math     43
10    5   math     66
11    6   math     77

<h1>pivot()

In [104]:
import pandas as pd
var = pd.DataFrame({"day":[1,2,3,4,5,6], 
                    "name":["a","b","c","a","b","c"],
                    "eng":[10,12,13,14,15,16], 
                    "math":[43,22,56,43,66,77]})
print(var)

   day name  eng  math
0    1    a   10    43
1    2    b   12    22
2    3    c   13    56
3    4    a   14    43
4    5    b   15    66
5    6    c   16    77


In [105]:
var.pivot(index="day",columns="name")

eng              math            
name     a     b     c     a     b     c
day                                     
1     10.0   NaN   NaN  43.0   NaN   NaN
2      NaN  12.0   NaN   NaN  22.0   NaN
3      NaN   NaN  13.0   NaN   NaN  56.0
4     14.0   NaN   NaN  43.0   NaN   NaN
5      NaN  15.0   NaN   NaN  66.0   NaN
6      NaN   NaN  16.0   NaN   NaN  77.0

In [106]:
var.pivot(index="day",columns="name", values="eng") #by passing values we can get perticuler pivot table column.

name     a     b     c
day                   
1     10.0   NaN   NaN
2      NaN  12.0   NaN
3      NaN   NaN  13.0
4     14.0   NaN   NaN
5      NaN  15.0   NaN
6      NaN   NaN  16.0

In [111]:
var.pivot_table(index="name", columns="day", aggfunc="sum", margins=True)  #by passing aggfunc we can calculate sum, min, max, mean data from df
                                                                   # by passing margins, it will return sum of each row in a table.

eng                                    math                          \
day      1     2     3     4     5     6 All     1     2     3     4     5   
name                                                                         
a     10.0   NaN   NaN  14.0   NaN   NaN  24  43.0   NaN   NaN  43.0   NaN   
b      NaN  12.0   NaN   NaN  15.0   NaN  27   NaN  22.0   NaN   NaN  66.0   
c      NaN   NaN  13.0   NaN   NaN  16.0  29   NaN   NaN  56.0   NaN   NaN   
All   10.0  12.0  13.0  14.0  15.0  16.0  80  43.0  22.0  56.0  43.0  66.0   

                 
day      6  All  
name             
a      NaN   86  
b      NaN   88  
c     77.0  133  
All   77.0  307